---
title: "Wordle"
format: html
editor: visual
---

## Quarto

```{r}
#Loading in my libraries
library(tidyverse)
library(sjmisc)

#Creating the load_dictionary function with filename as an argument
load_dictionary <- function(filename) {
    wlist <- read_csv(filename, col_names = TRUE) #reading in the table
    wlist <- word_list[["words"]] #providing the column name
}

#Loading in the datasets
scrabble <- "https://raw.githubusercontent.com/difiore/ada-datasets/main/google-10000-english-usa-no-swears.txt"
google <- "https://raw.githubusercontent.com/difiore/ada-datasets/main/collins-scrabble-words-2019.txt"

#Creating the solution_list using the load_dictionary function to bring in the google-10000-english-usa-no-swears.txt
solution_list <- load_dictionary(google)
str(solution_list) #doublecheck!

#Creating the valid_list using the load_dictionary function to bring in the collins-scrabble-words-2019.txt 
valid_list <- load_dictionary(scrabble)
str(valid_list) #doublecheck!
```

Step 2

```{r}
#Cutting the solution list so it only includes words already on the valid_list using the intersect() function
solution_list<- intersect(solution_list, valid_list)
```

Step 3  - Pick Solutions Function

```{r}
#
pick_solution <- function(word_list) {
    solution_options <- word_list[nchar(word_list) == 5] #Only including words that are five characters
    solution <- sample(solution_options, 1) #taking 1 random sample from the available five-letter words and labeling it as "solution"
    print(solution)
    vec_truesolution <- str_split(solution, "")[[1]] #taking the word chosen and splitting up each character across a vector
}

coolword <- pick_solution(solution_list) #exciting word!
```

Step 4 part A - Play Wordle function

```{r}
#creating the play_wordle function 
#arguments required including the correct word, the options available to choose from, and the tries required)
play_wordle <- function(coolword, valid_list, num_guesses = 6) {

    word_length <- length(coolword) #amount of characters in correct word
    
    #Instructions for gameplayer:
    print(paste0("You have ", num_guesses, " chances to guess a five-letter word")) 
    
    #Creating the vector of letters that will appear for choice
    letters <- LETTERS 
    
    #Matrix labeled previous_guesses
    previous_guesses <- data.frame(matrix(nrow = num_guesses, ncol = word_length))
    
    #Matric labeled previous_results
    previous_results <- data.frame(matrix(nrow = num_guesses, ncol = word_length))
    
    #Creating the loop for the number of guesses out of six total
    for (i in 1:num_guesses)  { 
      #Printing the remaining letters availble
        print(paste0(c("Letters left: ", letters), collapse = " ")) 
  
      #Printing "Pick word ___!" to have the user return a response
        guess <- readline(paste0("Pick word ", i, "! -> ")) %>% 
            toupper() #match capitalization

        #Using while() loop to validate the input word is the correct word length and return with readline response if not validated
         while (nchar(guess) != word_length) { 
            guess <- readline(paste("WRONG! Five characters are needed buddy...")) %>%
                toupper()
         }
        #Using the while() loop to validate the input word is on the valid_list by using 'not in' operator
        while (guess %nin% valid_list) {  
            guess <- readline(paste0("She doesn't even go here, pick another one for round ", i)) %>%
                toupper()
        }
        #Breaking up the users guess into a character string vector using str_split from earlier
        guess <- str_split(guess, "")[[1]] 
        print(guess)
        #using my evaluate_guess function to return the results of each character placement
        result <- evaluate_guess(guess, coolword)
        #Updating my keyboard of availble functions using the setdiff() function to find the difference between the remaining_letters vector and the guess
        letters <- setdiff(letters, guess) 
       
         #Adding previous guesses and results into the matrix
        previous_guesses[i, ] <- guess
        previous_results[i, ] <- result
        
        #IF all letters in guess vector match coolword vector
         if (all(result == "*")) { 
            previous_guesses <- previous_guesses %>%
                na.omit()
            previous_results <- previous_results %>%
                na.omit()
            print(paste("CONGRATS! You are one smart cookie!"))
            previous_guesses <- previous_guesses %>%
                unite(everything(), sep = "", col = "guess", remove = TRUE)
            previous_results <- previous_results %>%
                unite(everything(), sep = "", col = "result", remove = TRUE)
            game_save <- data.frame(guess = previous_guesses, result = previous_results)
            print(game_save)
        }
}
    #IF letters are not matching the coolword
    print(paste0("WRONG! The correct cool word was ", paste0(coolword, collapse = "")))

    previous_guesses <- previous_guesses %>%
        unite(everything(), sep = "", col = "guess", remove = TRUE)
    previous_results <- previous_results %>%
        unite(everything(), sep = "", col = "result", remove = TRUE)
    game_save <- data.frame(guess = previous_guesses, result = previous_results)
    print(game_save)
}


#Creating the evaluate_guess function with the user guess and the chosen word as arguments
evaluate_guess <- function(guess, coolword) {
    word_length <- length(coolword) #Length of coolword; always 5
    resulttxt <- rep("-", word_length) #Creating the cool word length as a vector

    #Creates two tables that count how many times each distinct letter appears in guess and in coolword respectively
    guess_count <- tibble(letter = guess) %>%
        group_by(letter) %>%
        summarize(n_in_guess = n())
    solution_count <- tibble(letter = coolword) %>%
        group_by(letter) %>%
        summarize(n_in_solution = n())
   
     #Joins the two counts by letter and mutates 
    counts <- inner_join(guess_count, solution_count, by = "letter") %>%
        mutate(to_clear = n_in_guess - n_in_solution) %>%
        filter(to_clear > 0) %>% #Keeps only letters where guess has more occurrences than the solution
        select(letter, to_clear)

    for (i in 1:word_length) {
        resulttxt[i] <- case_when(guess[i] %in% coolword & guess[i] == coolword[i] ~
            "*", guess[i] %in% coolword & guess[i] != coolword[i] ~
              "+", guess[i] %nin%
            coolword ~ "-")
      
        for (s in counts$letter) {
            if (guess[i] == s & text_result[i] != "*" & counts[counts$letter == s,
                ]$to_clear > 0) {
                resulttxt[i] <- "-"
                counts[counts$letter == s, ]$to_clear <- counts[counts$letter ==
                  s, ]$to_clear - 1
            }
        }
    }
    return(resulttxt)
}
```

```{r}
play_wordle(coolword, valid_list)

RADIO
```
